name: Setup, Build & Test modules
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      platform:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust
        if: inputs.platform == 'windows'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-msvc
      - name: Setup Rust
        if: inputs.platform != 'windows'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable # Modules should work on stable, not just nightly
      - name: Run tests
        run: |
          cargo test -p llrt_modules
