name: build artifacts
on: workflow_call

jobs:
  build-artifacts:
    strategy:
      fail-fast: ${{ startsWith(github.ref, 'refs/tags/') }}
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
            release: x64
            toolchain: nightly-x86_64-pc-windows-gnu
            RUSTFLAGS: -C target-feature=+crt-static
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            release: x64
            toolchain: nightly
          - os: ubuntu-latest
            platform: linux
            arch: aarch64
            release: arm64
            toolchain: nightly
          - os: macos-latest
            platform: darwin
            arch: x86_64
            release: x64
            toolchain: nightly
          - os: macos-latest
            platform: darwin
            arch: aarch64
            release: arm64
            toolchain: nightly

    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
      release: ${{ matrix.release }}
      toolchain: ${{ matrix.toolchain }}
